"""Corpus ranker — IDF inverted-index retrieval over the keeping (floor primitive #7).

The same distinctiveness-floored IDF ranker as 1.0 (api/cards.py): a card surfaces only
if it matches a genuinely DISTINCTIVE query token, so common words don't drag in
off-topic cards. Surface-filtered: the secular reach (.com) sees only secular-tagged
cards; the witness surface (.org) sees the whole keeping. The corpus is loaded from
cards.jsonl (data, gitignored — generated by tools/migrate_cards.py).

The 1.0 authority-tier boost (scripture/creed/... rank higher) is intentionally omitted
from the secular core — it is witness-surface ranking and belongs with the .org overlay.
"""
from __future__ import annotations

import json
import math
import os
import re
import threading
from pathlib import Path
from typing import Any, Dict, List, Optional

from .ops import STUB_BODY_CHARS  # the one definition of "stub" — never redefined here

# A query token must be at least this distinctive (high IDF) to count as a real hit.
# Tuned for a large corpus; lower it for small fixtures.
MIN_DISTINCTIVE_IDF = 1.5

_FIELDS = ("title", "body", "bands", "source")

# How-to INTENT markers (verbs only — no nouns like "fire"/"water", so this never hijacks a topic
# search). Used only to lift the practical field library when a question is clearly practical; and
# safe by construction — the boost multiplies a survival card only if it ALREADY matched the query.
_PRACTICAL = frozenset({
    "how", "build", "make", "start", "light", "purify", "treat", "cure", "stop", "find", "tie",
    "preserve", "store", "grow", "plant", "raise", "signal", "navigate", "cook", "fix", "repair",
    "survive", "forage", "trap", "prepare", "canning", "dry", "sharpen", "filter", "splint",
})


def _tokens(text: str) -> List[str]:
    return re.findall(r"[a-zA-Z][a-zA-Z']{1,}", (text or "").lower())


def _card_text(card: dict) -> str:
    src = card.get("source") or {}
    return " ".join([
        card.get("title", ""),
        (card.get("body", "") or "")[:1000],
        " ".join(card.get("bands") or []),
        src.get("ref", ""),
        src.get("label", ""),
    ]).lower()


PUBLIC_STAGES = frozenset({"public", "featured"})

# Disallowed-to-REDISTRIBUTE license markers. Two classes are a legal issue to serve publicly:
# share-alike (CC-BY-SA — its viral copyleft could pull the WHOLE corpus under SA) and
# non-commercial (CC-BY-NC* — forbids the free-to-all use that is the point). PD / CC0 / CC-BY
# (attribution-only) are fine, credited by each card's own source label. Mirror of the mint-side
# guard in tools/card_sources.py (_DISALLOWED_LICENSE) — the two boundaries stay in step.
_DISALLOWED_LICENSE = ("cc-by-sa", "cc by-sa", "share-alike", "sharealike",
                       "cc-by-nc", "cc by-nc", "non-commercial", "noncommercial")
# Legacy sources that ARE disallowed-license but whose cards were minted before the guard and carry
# only the SOURCE NAME in their label, never the license string. OEIS (CC-BY-NC-SA) is the live
# case — 6,000 cards served under a bare "OEIS — …" label, slipping the marker scan (found 2026-08-08
# in the pre-launch shelf audit). Matched by source name (label + url) so the name alone withholds.
_DISALLOWED_SOURCE = ("oeis", "phoible", "drugcentral")

# Back-compat alias: the flag on a frozen-shelf stub and older callers is still named `share_alike`.
_SHARE_ALIKE = _DISALLOWED_LICENSE


def _is_share_alike(card: dict) -> bool:
    """True iff a card declares a license we may not publicly REDISTRIBUTE — share-alike (CC-BY-SA)
    or non-commercial (CC-BY-NC*) — OR names a known such source. Read from the free-text source
    label, `source.url`, and any `extra.license` (a structured `license` field would be more robust;
    tracked as a follow-up). HYG + PHOIBLE match by their CC-BY-SA label; OEIS matches by source name.

    A FROZEN-SHELF STUB drops `source`/`extra` to save memory, so it carries a precomputed
    `share_alike` bool (set at stub-build time while the label was still present) — honoured here
    first, so is_public() judges a stub exactly as it judges the full card. Without this, search
    (which runs over stubs) leaked CC-BY-SA cards that card_get correctly withheld (found live)."""
    flag = card.get("share_alike")
    if flag is not None:
        return bool(flag)
    src = card.get("source")
    label = (src.get("label") if isinstance(src, dict) else "") or ""
    url = (src.get("url") if isinstance(src, dict) else "") or ""
    extra = card.get("extra")
    lic = (extra.get("license") if isinstance(extra, dict) else "") or ""
    if any(m in (str(label) + " " + str(lic)).lower() for m in _DISALLOWED_LICENSE):
        return True
    # a known disallowed source recognised by name, for legacy cards whose label lacks the license
    return any(s in (str(label) + " " + str(url)).lower() for s in _DISALLOWED_SOURCE)

# Larger than any reachable TF-IDF score, so cards holding the query's rarest word form a
# strictly higher tier than those that do not. A partition, not a weight: no amount of
# repeating a common word can cross it.
SUBJECT_TIER = 1000.0

# A theory card outranks an incidental mention of the same words. Deliberately a WEIGHT and not a
# tier: the subject partition still decides who is in the running, and this only orders those who
# already are. Set at 4.0 — above the survival field library's 3.0 (a how-to should still win a
# how-to question) and well under the exact-title 9.0, so naming a card by its title still wins.
THEORY_WEIGHT = 4.0

# THE RANKER WAS BLIND TO SUBSTANCE VS HEADWORD (docs/SOP/subsystems/keeping.md's own "Refine" —
# the highest-leverage open item, 2026-09-02). ~67% of the keeping are stubs (a pronunciation
# guide, a bare title+link — ops.STUB_BODY_CHARS defines the line), and the subject partition
# above is lexical presence only: it can tell "about this" from "not about this," never a thin
# gloss from a real excerpt that answers the question. A weight, not a tier, like THEORY_WEIGHT —
# it only ever reorders cards the partition already admitted. Set modestly (well under
# THEORY_WEIGHT) because it distinguishes within EVERY tier a query reaches, not one narrow shelf.
SUBSTANCE_WEIGHT = 2.0


def is_public(card: dict) -> bool:
    """True iff a card may appear on ANY public read path — an ALLOWLIST, not a denylist.
    ONE source of truth (graph.py imports this too, so the two can never diverge): every
    stage except public/featured — private, public_review, archived, quarantine, retracted —
    is withheld. A denylist here (archived/quarantine only) is exactly what leaked the
    operator's private cards onto the public surface. On top of the stage allowlist, two
    withholding guards (more restrictive, never less): share-alike-licensed cards (CC-BY-SA —
    a legal issue to redistribute) and generated cards (the conduit contract) never go public."""
    if not isinstance(card, dict) or card.get("retracted"):
        return False
    if (card.get("lifecycle_stage") or "public") not in PUBLIC_STAGES:
        return False
    # LICENSE (red team 2026-08-06, Matt's call "drop what could get us in trouble"): never publicly
    # REDISTRIBUTE share-alike content — its copyleft could pull the whole corpus under SA. Withheld
    # here, not deleted (the bodies stay archived on the drive). A PD stub card ABOUT each such source
    # still serves, so the shelf is not a silent hole. See _is_share_alike.
    if _is_share_alike(card):
        return False
    # The conduit contract at the serving boundary: a generated card is never served publicly.
    if card.get("generated") is True:
        return False
    return True


# ── The freeze (D4) — the heavy shelves ride the shards, the graph stays home ────────────
# Matt, 2026-07-27/28: the two processes held ~2.8 GB RSS each with every shelf resident.
# Profiled per-structure (2026-07-28): dictionary/gutenberg/geography/taxonomy carry 258.7 MB
# serialized, and ~70% of it is body/bands/extra/source — none of which the GRAPH needs.
# With CONCORDANCE_FREEZE_SHELVES set (and shards present), those shelves load as STUBS:
# identity + connections stay resident so the nesting stays whole (zero orphans, titles
# findable); bodies, bands, and provenance rehydrate from the SQLite shards on read.
# Opt-in and reversible: unset the env and everything loads resident exactly as before.

# What a stub keeps: identity, the public/withheld boundary, and the graph. `retracted`,
# `lifecycle_stage`, `generated`, and the computed `share_alike` bool stay so is_public() judges a
# stub exactly as it judges the full card — the license lives in `source` (dropped on a stub), so
# it is precomputed at stub-build time (search runs on stubs; without this it leaked CC-BY-SA).
_STUB_KEEPS = frozenset({"id", "title", "shelf", "surface", "kind", "box", "visibility",
                         "lifecycle_stage", "retracted", "generated", "share_alike", "connections"})


def frozen_shelves() -> frozenset:
    """The shelves currently riding the shards — empty unless BOTH the env names them AND the
    shards exist (bodies are never shed without a place to rehydrate from)."""
    env = os.environ.get("CONCORDANCE_FREEZE_SHELVES", "").strip()
    if not env:
        return frozenset()
    from . import corpus_db
    if not corpus_db.available():
        return frozenset()
    return frozenset(s.strip() for s in env.split(",") if s.strip())


def rehydrate(card: Optional[dict]) -> Optional[dict]:
    """The FULL card for a frozen stub — body, bands, provenance — read from its shard.
    The resident stub is never mutated; the LIVE graph (bridges, minted edges) carries over
    the stored copy. If the shard cannot answer, the stub itself returns — id, title, and
    connections in hand, never a silent hole."""
    if not card or not card.get("frozen"):
        return card
    from . import corpus_db
    if not corpus_db.available():
        return card
    corpus_db.thaw_for(card.get("shelf") or "")
    full = corpus_db.get_card(card.get("id", ""))
    if not isinstance(full, dict):
        return card
    full["connections"] = card.get("connections", full.get("connections") or [])
    return full


class Corpus:
    """An indexed, searchable set of cards (id -> card dict)."""

    def __init__(self, cards: Dict[str, dict], min_idf: float = MIN_DISTINCTIVE_IDF,
                 df_extra: Optional[Dict[str, int]] = None):
        self.cards = cards
        self.min_idf = min_idf
        self._by_token: Dict[str, List[str]] = {}
        # extra document frequency from frozen stubs' full text (streamed out of load_cards) —
        # the tokens themselves live on the shard, but their COUNTS stay here so the corpus-wide
        # IDF statistics are identical whether a shelf is frozen or resident
        self._df_extra: Dict[str, int] = dict(df_extra) if df_extra else {}
        for cid, c in cards.items():
            if not is_public(c):
                continue
            for t in set(_tokens(_card_text(c))):
                self._by_token.setdefault(t, []).append(cid)
        # CANONICAL POSTINGS. Two corpora over the same cards must rank identically whatever
        # order the cards arrived in — invariant I of tests/test_retrieval_invariants.py. Without
        # this, cap admission and tie order both follow insertion order, and "same corpus, same
        # query" can rank differently across builds. Sorted once at load; never at query time.
        for v in self._by_token.values():
            v.sort()
        self._n = max(1, len(self._index_card_ids()))

    def footprint(self, sample: int = 400) -> Dict[str, Any]:
        """What this corpus costs in memory, BY STRUCTURE — measured, not believed.

        Matt, 2026-08-01, questioning the freeze: *"The concept is we keep the corpus frozen and
        only unthaw and carry what is necessary, but that may be a faulty concept."*

        Freezing 24 shelves took each engine from ~2.8 GB to ~1.7 GB, so it worked — but 25,087
        resident cards costing 1.7 GB is ~68 KB PER CARD, which no card body explains. That points
        at the index rather than the text, and the difference decides an architecture: if the
        weight is `_by_token`, moving bodies to shards treated a symptom and one on-disk store
        would be both smaller and simpler. If it is `cards`, freezing is doing exactly its job.

        A belief cannot settle that. This can, from the live process, without loading anything.

        SAMPLED, AND IT SAYS SO. Walking 25,000 nested dicts on a serving box is not free, so the
        card cost is measured over `sample` of them and scaled — the returned record carries the
        sample size and the population so nobody reads an estimate as a census.
        """
        import sys as _sys

        def _deep(obj, _seen=None) -> int:
            """Recursive size of a small object graph — dicts, lists and strings, no cycles here."""
            _seen = _seen if _seen is not None else set()
            if id(obj) in _seen:
                return 0
            _seen.add(id(obj))
            total = _sys.getsizeof(obj)
            if isinstance(obj, dict):
                for k, v in obj.items():
                    total += _deep(k, _seen) + _deep(v, _seen)
            elif isinstance(obj, (list, tuple, set)):
                for x in obj:
                    total += _deep(x, _seen)
            return total

        ids = list(self.cards)
        n_cards = len(ids)
        taken = ids[:max(1, min(sample, n_cards))]
        per_card = (sum(_deep(self.cards[i]) for i in taken) / len(taken)) if taken else 0
        cards_bytes = int(per_card * n_cards)

        # The inverted index: token -> [card_id, ...]. The POSTINGS are the thing to count — every
        # one is a pointer in a list, and the lists themselves carry per-object overhead.
        postings = sum(len(v) for v in self._by_token.values())
        idx_bytes = _sys.getsizeof(self._by_token)
        idx_bytes += sum(_sys.getsizeof(t) + _sys.getsizeof(v) for t, v in
                         list(self._by_token.items())[:sample])
        if len(self._by_token) > sample:
            idx_bytes = int(idx_bytes / max(1, min(sample, len(self._by_token)))
                            * len(self._by_token))
        idx_bytes += postings * 8                      # one pointer per posting

        df_bytes = _sys.getsizeof(self._df_extra) + sum(
            _sys.getsizeof(k) + 28 for k in list(self._df_extra)[:sample])

        return {
            "cards": n_cards, "tokens": len(self._by_token), "postings": postings,
            "df_extra_tokens": len(self._df_extra),
            "bytes": {"cards": cards_bytes, "token_index": idx_bytes, "df_extra": df_bytes,
                      "total": cards_bytes + idx_bytes + df_bytes},
            "mb": {"cards": round(cards_bytes / 1048576, 1),
                   "token_index": round(idx_bytes / 1048576, 1),
                   "df_extra": round(df_bytes / 1048576, 1),
                   "total": round((cards_bytes + idx_bytes + df_bytes) / 1048576, 1)},
            "measured_over": len(taken), "population": n_cards,
            "note": "card cost is sampled and scaled; index cost is counted postings + sampled "
                    "key/list overhead. An estimate, and labelled as one.",
        }

    def add_card(self, card: dict) -> None:
        """Insert one card into the live corpus AND its token index — so a just-minted
        verification is searchable immediately, no restart. Idempotent by id."""
        cid = card.get("id")
        if not cid:
            return
        self.cards[cid] = card
        if is_public(card):
            for t in set(_tokens(_card_text(card))):
                self._by_token.setdefault(t, [])
                if cid not in self._by_token[t]:
                    self._by_token[t].append(cid)
            self._n = max(1, len(self._index_card_ids()))

    def _index_card_ids(self) -> set:
        ids: set = set()
        for cids in self._by_token.values():
            ids.update(cids)
        return ids

    def _idf(self, query_tokens: set) -> Dict[str, float]:
        return {t: max(0.0, math.log(self._n / (len(self._by_token.get(t, ()))
                                                + self._df_extra.get(t, 0) + 1)))
                for t in query_tokens}

    def _candidates(self, query_tokens: set, max_candidates: int = 600,
                    seat_family: Optional[set] = None) -> List[str]:
        """Candidate cards, RAREST TOKENS FIRST — the cap must never starve the subject.

        This was a heisenbug that survived every gate: tokens were taken in SET-ITERATION order,
        which is hash-seed dependent and re-rolls on every process restart. For "southern
        baptists" (df 2,702 vs 160), whichever token iterated first flooded the 600-candidate cap
        — one restart returned 8 Baptist histories, the next restart returned 1, for the same
        query on the same corpus. A ranking that changes with a restart is a ranking that cannot
        be trusted or tested. Iterating by ascending document frequency is deterministic and puts
        the words the question is actually about beyond starvation: a common word can never crowd
        out a rare one, only fill the seats the rare ones left.
        """
        counts: Dict[str, int] = {}
        exempt = set(seat_family or ())
        for qt in sorted(query_tokens, key=lambda t: (self._df(t) or 10**9, t)):
            uncapped = qt in exempt
            for cid in self._by_token.get(qt, []):
                if cid in counts:
                    counts[cid] += 1          # a seated card still collects its later matches
                elif uncapped or len(counts) < max_candidates:
                    counts[cid] = 1
        # THE SEAT IS NEVER CAPPED. The cap is a performance guard for common-word floods; the
        # partition's upper tier is DEFINED by holding the seat, so every seat-holder must reach
        # scoring or the tier lies by omission. Found when canonical (id-sorted) postings made
        # cap admission an alphabetical lottery and the survival how-to card lost it inside its
        # own token. Worst case is scoring one common seat's full postings (~the resident corpus,
        # 25k short texts) — the price of a tier that tells the truth.
        return sorted(counts, key=lambda x: -counts[x])

    def _df(self, token: str) -> int:
        return len(self._by_token.get(token, ())) + self._df_extra.get(token, 0)

    def _present_form(self, token: str) -> str:
        """The form of this word the corpus ACTUALLY CONTAINS — naive singular/plural only.

        "Southern Baptists" returned nothing from a library full of Baptist material, because
        there is no stemming anywhere: the subject partition demanded the exact token "baptists",
        the corpus says "baptist", and _idf hands an UNSEEN token the highest rarity of all —
        df=0 is the rarest thing there is — so the absent plural won the subject seat and then
        partitioned out the entire keeping. An empty shelf reported by a full library.

        Only trailing-s/es variants, only when the token itself is absent, and only toward a form
        that exists: anything cleverer is a stemmer, and a stemmer quietly rewrites what the
        person asked.
        """
        if self._df(token) > 0 or len(token) < 4:
            return token
        candidates = [token + "s", token + "es"]
        if token.endswith("es"):
            candidates.append(token[:-2])
        if token.endswith("s"):
            candidates.append(token[:-1])
        for v in candidates:
            if len(v) >= 3 and self._df(v) > 0:
                return v
        return token

    def _with_variants(self, query_tokens: set) -> set:
        """Query tokens plus BOTH numbers of each, wherever that form exists in the index.

        The first version added a variant only when the asked form was ABSENT (df=0) — which left
        a hole measured live on 2026-08-02: "methodists" has df=31, so no "methodist" was added,
        `common = query ∩ doc` came up empty against the singular-only Methodist / Wesleyan voice
        card, and the card died at the no-common-tokens gate BEFORE the family partition could
        fire. The partition can only judge what scoring lets through, so the family has to enter
        at the tokens, not just at the verdict. Only forms the index actually contains are added —
        expansion never invents a word the corpus has never seen.
        """
        out = set(query_tokens)
        for t in query_tokens:
            out.add(self._present_form(t))
            for v in self.subject_family(t):
                if self._df(v) > 0:
                    out.add(v)
        return out

    @staticmethod
    def subject_family(subject: Optional[str]) -> set:
        """The subject in both numbers — "methodists" and "methodist" are one subject.

        The partition demanded the exact subject form, so the Methodist / Wesleyan voice card
        (which says "Methodist", singular) was partitioned OUT of a search for "methodists" —
        live, on a shelf that plainly holds the tradition. A card about the singular IS about the
        plural. Trailing s/es only; anything cleverer is a stemmer.
        """
        if not subject:
            return set()
        fam = {subject, subject + "s"}
        if subject.endswith("es") and len(subject) > 4:
            fam.add(subject[:-2])
        if subject.endswith("s") and len(subject) > 3:
            fam.add(subject[:-1])
        return fam

    def _subject_of(self, query_tokens: set, idf: Dict[str, float]) -> Optional[str]:
        """The rarest query word — what the question is ACTUALLY about.

        "Wesleyan Church" is about Wesleyans. "Church" is in half the library. And the seat must
        be held by a form the corpus CONTAINS: an absent token has df=0, which _idf reads as
        maximal rarity, so without the present-form step a typo or a plural would always win the
        seat and then partition out everything (the Southern Baptists failure).
        """
        if not query_tokens:
            return None
        chosen = max(query_tokens, key=lambda t: idf.get(t, 0.0))
        return self._present_form(chosen)

    def _score(self, card: dict, query_tokens: set, idf: Dict[str, float],
               subject: Optional[str] = None) -> float:
        """TF-IDF over the card text — with a HARD PARTITION on the subject word.

        Matt, 2026-08-01, on asking for the Wesleyan Church: *"It currently gives a bunch of not
        useful information... just random cards. Right now it's a dud."* He was right, and the
        cause was here.

        The score is sum(tf x idf) / log(len). TERM FREQUENCY OF A COMMON WORD OVERWHELMS THE
        PRESENCE OF A RARE ONE: a treatise that says "church" forty times outscores a card that
        says "Wesleyan" once. So "Wesleyan Church" returned Belgic Article 29 and Heidelberg Q85 —
        REFORMED confessions — to someone asking about a Wesleyan church. Not merely irrelevant:
        it hands a reader the tradition that disagrees with theirs, on the points they care about.
        And because the connection cloud then builds around the top hit, the whole neighbourhood
        came back Reformed. One bad first card poisons everything downstream.

        A WEIGHT WOULD NOT FIX THIS — any multiplier can be out-shouted by enough repetitions.
        This is a PARTITION: a card that does not contain the subject word cannot outrank one that
        does, however often it repeats the rest. The shape decides, not a tuned constant, so no
        amount of term frequency can reverse the flow. `SUBJECT_TIER` is larger than any reachable
        TF-IDF score by construction, which makes the two tiers non-overlapping.

        A one-word query is its own subject, so this changes nothing there.
        """
        doc_tokens = _tokens(_card_text(card))
        if not doc_tokens:
            return 0.0
        common = query_tokens & set(doc_tokens)
        if not common:
            return 0.0
        if max((idf.get(t, 0.0) for t in common), default=0.0) < self.min_idf:
            return 0.0
        counts = {t: 0 for t in common}
        for t in doc_tokens:
            if t in counts:
                counts[t] += 1
        # A frozen stub's text is its TITLE alone — scoring it by its real (tiny) length would
        # hand it an artificial length-normalization boost over full resident cards (caught by
        # the probe battery: gutenberg title stubs outscored the Bible-facts answerer). Score
        # stubs against a typical FULL card's document length instead, so freezing a shelf
        # never changes its cards' rank.
        doc_len = max(len(doc_tokens), 150) if card.get("frozen") else len(doc_tokens)
        score = sum(counts[t] * idf.get(t, 0.0) for t in common) / math.log(doc_len + 10)
        if len(common) == len(query_tokens):
            score *= 1.5
        # SUBSTANCE VS HEADWORD. Applied to the BASE score, before the tier addition below, so it
        # only ever reorders cards WITHIN whichever tier they already earned: a boosted stub still
        # cannot cross into the subject tier alone (base scores never approach SUBJECT_TIER's
        # scale — see its own comment), and among cards that already hold the subject, a real
        # answer now pulls ahead of a bare pointer that merely names it. A frozen card scored here
        # BEFORE rehydration still carries its true (stripped) stub body, so this correctly treats
        # it as a stub on that first pass; `search()` rehydrates and re-scores any frozen card that
        # clears zero, so the score actually used for ranking always reflects the real body.
        if len(str(card.get("body") or "")) >= STUB_BODY_CHARS:
            score *= SUBSTANCE_WEIGHT
        # THE PARTITION. Holding the subject word puts a card in the upper tier outright —
        # in EITHER number: a card that says "Methodist" is about "methodists" (the singular-only
        # voice card was partitioned out of a plural search, live, 2026-08-02). The seat is
        # chosen among the ASKED words, never among expansion variants — a rare junk variant
        # ("southerns") once stole the seat from "baptists". Search computes it once and passes
        # it in; never an instance attribute, because searches run concurrently across threads.
        if subject is None:
            subject = self._subject_of(query_tokens, idf)
        if subject and (self.subject_family(subject) & set(doc_tokens)):
            score += SUBJECT_TIER
        return float(score)

    def search(self, query: str, limit: int = 25, include_witness: bool = True,
               shelves: Optional[set] = None) -> List[dict]:
        """Ranked search over the keeping.

        The keeping is ONE SHARED library: by default BOTH surfaces draw the whole thing
        — the .com includes the religious cards too (Matt, 2026-06-26: "the religious
        cards can be included"; "we are not hiding anything"). `include_witness=False`
        gives an optional scrubbed view if a caller ever wants secular-only results.

        `shelves` (a set) restricts the search to those shelves — the DECK fast-path (the Hare):
        scoring only the deck's cards instead of the whole keeping. None = the whole library
        (the Tortoise). A deck search that comes up short can always fall back to the full one."""
        # A truthy non-string query (e.g. an int from an uncoerced MCP tool call — args.get("query")
        # with no str() at the call site) would otherwise crash here: "query or ''" only substitutes
        # the fallback for a FALSY query, so a non-empty int/list survives and .lower() raises
        # AttributeError deep inside _tokens(). This is the one shared search entry point (the HTTP
        # /search route and /ask already coerce before calling in, but the MCP search tool does not)
        # — coerce once, here, so every caller is safe regardless of what reaches this function.
        query = str(query) if query else ""
        # STOPWORDS ARE NOT A SUBJECT — the same rule as the shard matcher, from the same list, so
        # the two doors can never drift apart.
        #
        # IDF alone does NOT solve this, which is why the bug survived here after the shard side was
        # fixed. `_idf` is log(n / (df + 1)): a word in 20k of 478k cards still scores ~3.2, small
        # next to a rare term but very far from zero. So when the DISTINCTIVE word matches nothing
        # — "what is Mahavira", and we hold no Mahavira — the only tokens left contributing are
        # "what" and "is", cards containing them score above zero, and the reader is handed Marcus
        # Aurelius as though it were an answer. Measured live 2026-08-01 on the 1,000-probe assay.
        #
        # A gap must be allowed to report itself; a miss is what feeds the want list. Dropping the
        # stopwords before candidates or scoring means nothing can be retrieved on their strength
        # alone. A query made only of stopwords asks about nothing and returns nothing.
        from .corpus_db import _STOP          # one list, both matchers (corpus_db imports nothing here)
        asked = {t for t in _tokens(query) if t not in _STOP}
        # THE PRESENT FORM RIDES ALONG — for scoring. The SUBJECT SEAT is chosen among the words
        # actually ASKED: expansion once added "southerns" (a rare variant of a common word,
        # df tiny so idf huge) and the junk variant stole the seat from "baptists". Variants
        # widen what can match; they never redefine what the question is about.
        query_tokens = self._with_variants(asked)
        # the seat belongs to the words actually asked — computed once, passed to scoring;
        # never instance state (searches run concurrently across handler threads)
        seat = self._subject_of(asked, self._idf(asked)) if asked else None
        if not query_tokens:
            return []
        idf = self._idf(query_tokens)
        # exact-match targets: the query as typed, and its canonical verse forms — so a verse
        # lookup ("Philippians 4:13", the most common human search) ranks the verse card first
        # instead of a fuzzy book match. Reuses the growth engine's one verse canonicalizer.
        from . import growth as _growth
        qn = " ".join((query or "").lower().split())
        q_exact = {qn} | {r.lower() for r in _growth.refs_in_text(query or "")}
        scored = []
        for cid in self._candidates(
                query_tokens, seat_family=(self.subject_family(seat) if seat else None)):
            c = self.cards.get(cid)
            if not c or not is_public(c):
                continue
            if not include_witness and c.get("surface") == "witness":
                continue
            if shelves is not None and c.get("shelf") not in shelves:
                continue
            s = self._score(c, query_tokens, idf, subject=seat)
            if s > 0 and c.get("frozen"):
                # rank-neutral freezing: a stub that matched on TITLE is re-scored on its real
                # text from the shard, so freezing a shelf never reorders results. Only stubs
                # passing the distinctiveness floor pay the point lookup (a handful per query).
                full = rehydrate(c)
                if full is not c:
                    c = full
                    s = self._score(c, query_tokens, idf, subject=seat)
            if s > 0:
                title_n = " ".join(str(c.get("title", "")).lower().split())
                ref_n = " ".join(str((c.get("source") or {}).get("ref", "")).lower().split())
                if title_n in q_exact or (ref_n and ref_n in q_exact and title_n in q_exact):
                    s *= 9.0                              # THE card for this exact reference/title
                elif q_exact and (title_n in q_exact or ref_n in q_exact):
                    s *= 4.0
                # a practical/how-to question prefers the practical field library over an
                # incidentally-titled book or species (so "build a fire" gets the how-to, not fire ants)
                if c.get("shelf") == "survival" and (_PRACTICAL & query_tokens):
                    s *= 3.0
                # A THEORY IS LOAD-BEARING (Matt, 2026-08-02: "Theories should be weighted heavier
                # than a standard card."). The theories shelf is 99 cards out of 550,000, each one
                # a thing the sciences actually run on, each now carrying its own place in the
                # assembled floor — what it rests on, what limits it, what shares its form. When a
                # reader's question touches one, the theory is the card that orients everything
                # else, so it outranks an incidental mention in a book that happens to use the
                # same word. Applied INSIDE the s > 0 branch, so it can only lift a card the
                # partition already admitted — a boost can never smuggle in an off-subject hit.
                elif c.get("shelf") == "theories":
                    s *= THEORY_WEIGHT
                scored.append((s, c))
        # a TOTAL order: equal scores tie-break on id, so the ranking is a function of the
        # cards and the query alone — never of construction order (invariant I)
        scored.sort(key=lambda x: (-x[0], str(x[1].get("id") or "")))

        # NEVER PAD THE TAIL WITH CARDS THAT MISS THE SUBJECT. The partition put subject-holders
        # in the upper tier, but ranking alone still let the leftovers fill the limit: live,
        # "Wesleyan Church" came back with six Wesleyan cards and then a Kensington church
        # directory and "Doctrines Objected to in the Church of Rome" at 7 and 8, purely to reach
        # eight. Padding a count with things a reader must discard is the same lie as a silent cap
        # — it reads as "here is what we hold" when two of them are noise.
        #
        # So when ANY card holds the subject word, only those are served. Six true results beat
        # eight with two lies, and the count then means what it says. (The shard merge already
        # excludes rather than demotes; this makes both halves of the rule behave alike, which
        # they did not, and that inconsistency is what reached the reader.)
        if scored and scored[0][0] >= SUBJECT_TIER:
            scored = [(s, c) for s, c in scored if s >= SUBJECT_TIER]
        return [c for _s, c in scored[:max(1, int(limit))]]


# ── module-level default corpus (lazy, from cards.jsonl) ─────────────────

_DEFAULT: Optional[Corpus] = None
_DEFAULT_LOCK = threading.Lock()


def _cards_path() -> Path:
    env = os.environ.get("CONCORDANCE_CARDS_JSONL", "").strip()
    if env:
        return Path(env)
    data = os.environ.get("CONCORDANCE_DATA_DIR", "").strip()
    return (Path(data) if data else Path("data")) / "cards.jsonl"


def load_cards(path: Optional[Path] = None,
               _df_out: Optional[Dict[str, int]] = None) -> Dict[str, dict]:
    """Load cards from a JSONL file into an id -> card dict. Empty if absent.

    `_df_out` (internal — default_corpus passes it): a dict that receives the document
    frequency of each frozen card's full-text-only tokens, streamed during the load so no
    per-card token list ever materializes. Corpus takes it as `df_extra`, keeping the
    corpus-wide IDF statistics identical whether a shelf is frozen or resident (the probe
    battery caught title-only indexing re-ranking two RESIDENT cards on an unrelated query)."""
    p = path or _cards_path()
    out: Dict[str, dict] = {}
    if not p.exists():
        return out
    frozen = frozen_shelves()

    def _keep(c: dict) -> None:
        # a frozen-shelf card loads as a stub — the graph resident, the weight on the shard
        if c.get("shelf") in frozen:
            full_toks = set(_tokens(_card_text(c)))
            _sa = _is_share_alike(c)   # compute on the FULL card, before the source label is dropped
            c = {k: v for k, v in c.items() if k in _STUB_KEEPS}
            c["frozen"] = True
            c["share_alike"] = _sa     # so is_public() withholds a share-alike stub too (search runs on stubs)
            if _df_out is not None:
                for t in full_toks - set(_tokens(_card_text(c))):
                    _df_out[t] = _df_out.get(t, 0) + 1
        out[c["id"]] = c

    with open(p, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                c = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(c, dict) and c.get("id"):
                _keep(c)
    # further sources that join the SAME graph as Scripture and the tradition:
    #   verified_cards.jsonl — minted live from sealed verifications (data-only, gitignored)
    #   reference_cards.jsonl — the deep reference work already in the verifiers (periodic table,
    #                           physical constants, …), carded and GIT-TRACKED so the content is
    #                           on github, not only in the code
    if path is None:
        #   works_cards.jsonl — The Works: every worked, engine-sealed demonstration carded as a
        #                       seed in the keeping (minted by compendium.build_all, data-only)
        for extra in ("receipt_cards.jsonl",     # every minted seal, carded — see cas._mint_receipt_card
                      "acquired_cards.jsonl",    # cards a person CHOSE from the want list's options
                                                 # (tools/shepherd_rounds.py --choose; source-to-source)
                      "verified_cards.jsonl", "reference_cards.jsonl", "keystone_seeds.jsonl",
                      "nesting_seeds.jsonl", "ncs_seeds.jsonl", "works_cards.jsonl", "theory_cards.jsonl",
                      "fieldkit_cards.jsonl", "playbook_cards.jsonl", "systems_cards.jsonl",
                      "access_tools_cards.jsonl",   # the connection to lawful free tools (logistics: tag onto paid carriers)
                      "church_cards.jsonl",         # the churches, calibrated from their own confessions (not judged)
                      "contributors_cards.jsonl",   # the builders of the Floor (historians/scientists/mathematicians), credited with love
                      "religions_cards.jsonl",      # the pre-Christian faiths as foreshadow (Acts 17) + the test of the spirits (1 John 4)
                      "survival_cards.jsonl",       # the field library — outdoor/survival/bushcraft/homestead, PD sources (serve the off-grid + destitute)
                      "comms_cards.jsonl",          # the communications shelf — radio & field comms (FCC/ITU/NOAA PD) for the mesh + off-grid (the whisper layer beside the field library)
                      "firstaid_cards.jsonl",       # the first-aid shelf — conservative field medicine (US Army FM 4-25.11 / CDC / WHO PD): stop bleeding, breathing, shock, rehydrate
                      "navigation_cards.jsonl",     # the navigation shelf — map/compass/celestial land nav (US Army FM 3-25.26 PD): find the way with no battery
                      "power_cards.jsonl",          # the off-grid power shelf — solar/battery/inverter/generator safety (DOE/NREL PD): keep the lights + the radio on
                      "sanitation_cards.jsonl",     # the sanitation shelf — hygiene/waste/disease prevention (WHO/CDC/Army PD): the disciplines that stop post-disaster illness
                      "water_cards.jsonl",          # the water shelf — the household water SYSTEM (EPA/CDC/FEMA PD): storage, rainwater, wells, filter types (beside survival's find/purify)
                      "food_cards.jsonl",           # the food-growing shelf — garden/soil/seed/season (USDA PD): raising food, beside survival's preserving
                      # The plumb-line: the whole Bible in the original tongues (Greek NT + Hebrew OT),
                      # one card per verse. Academics first. Spines root in the Word.
                      "scripture_spines.jsonl", "scripture_cards.jsonl",
                      # The OEIS core — the foundational integer sequences (academics: mathematics).
                      "oeis_spine.jsonl", "oeis_cards.jsonl",
                      # The tree of life — the recognizable organisms (academics: biology).
                      "taxonomy_spine.jsonl", "taxonomy_cards.jsonl",
                      # The languages of the earth — PHOIBLE/Glottolog (academics: linguistics).
                      "language_spine.jsonl", "language_cards.jsonl",
                      # More stored sources — RFCs (internet standards), Matthew Henry commentary,
                      # Spurgeon sermons, and the Compendium of Physical Activities (METs).
                      "reference_extra_spines.jsonl", "reference_extra_cards.jsonl",
                      # Acquired: the Great Books — Project Gutenberg (~77k stub cards -> the full text).
                      "gutenberg_spine.jsonl", "gutenberg_cards.jsonl",
                      # Acquired: history — dated events from Wikidata (CC0), stub -> the full record.
                      "history_spine.jsonl", "history_cards.jsonl",
                      # The study tables (Harmony of the Gospels + the OT/NT/Church-History
                      # Timeline) carded, so the events are IN the keeping — findable by /search,
                      # walkable in the graph/brain, routable by wayfinding — and not marooned
                      # behind their own two routes. Minted by tools/card_study_tables.py.
                      "study_spines.jsonl", "study_cards.jsonl",
                      # The Biblical Encyclopedia as Cards — Easton's 3,962 entries, stub+link
                      # into /characters, boxed by category (the card-catalog drawers). Minted by
                      # tools/card_encyclopedia.py.
                      "encyclopedia_cards.jsonl",
                      # The domain reference cores (GAPS G1/G2): a spine per domain the engine
                      # can actually check, plus one WORKED-CHECK card per claim — the inputs,
                      # the engine's verdict, and the falsehood it refuses. Substance minted from
                      # runs that happened; nothing minted for an unproven domain.
                      "domain_core_cards.jsonl",
                      # The commentaries carded VERSE BY VERSE (44,371 cards, avg 1,462 chars of
                      # the commentator's own PD words, 99% linked to their verse by a found
                      # edge). Rides the `commentary` shelf -> the `word` shard, so the bodies
                      # are frozen freight and the resident cost is a stub.
                      "commentary_verse_cards.jsonl",
                      # The practical stores carded (seeding loop, practical pass 1): the
                      # apothecary monographs, the verified almanac, the coach curriculum —
                      # substance we already held that had no card at all.
                      "practical_cards.jsonl",
                      # Nave topical index SCANNED into topics + speaks_to edges (structure
                      # taken, the work's own text left with the work).
                      "topical_cards.jsonl",
                      # THE RECURRING ARCHITECTURE (tools/card_doctrine.py) — concepts gathered
                      # from Matt's six planning documents, which describe one pattern in six
                      # materials. Carried as concepts, never adopted as policy: each card names
                      # its document and says where the idea already bears weight here.
                      "doctrine_cards.jsonl",
                      # ISBE 1915 (D5) — 9,380 scholarly stub cards; the full public-domain
                      # article renders from data/acquisitions/isbe.db on the card page.
                      "isbe_cards.jsonl",
                      # The Corpus — technical, academic cards minted from the stored sources
                      # (nuclides, stars, foods, ports, indicators, …); always growing.
                      "source_spines.jsonl", "source_cards.jsonl", "web_cache.jsonl",
                      # The harvested map — inline SEMANTIC edges minted as sealed connection cards
                      # (cites, proof-texts, sections, families, grafts) so the constellation reflects
                      # the whole keeping. The member_of skeleton stays the floor tree's (tools/mint_edges.py).
                      "minted_edges.jsonl"):
            xp = p.parent / extra
            if not xp.exists():
                continue
            with open(xp, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        c = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if isinstance(c, dict) and c.get("id"):
                        _keep(c)
        for overlay in ("reference_bridges.jsonl", "keystone_bridges.jsonl",
                        "nesting_bridges.jsonl", "works_bridges.jsonl", "element_bridges.jsonl",
                        "ncs_bridges.jsonl"):
            _apply_bridges(out, p.parent / overlay)
    return out


# inverse labels for DIRECTIONAL (hierarchical) edges, so the reciprocal points the other way and
# the floor can be walked as a tree. Anything not here is treated as symmetric (lateral) — the
# reciprocal keeps the same label (shares_scripture, same_family, names_the_created_thing, …).
_INVERSE_REL = {
    "member_of": "has_member", "part_of": "has_part", "nested_in": "contains",
    "figure_of": "has_figure", "pre_registered_validation_of": "validated_by",
    "leads_to": "reached_from", "points_beyond_itself": "pointed_to_by",
}


def _apply_bridges(cards: Dict[str, dict], overlay: Path) -> None:
    """Graft the two trees: apply the git-tracked reference→Scripture bridges reciprocally onto
    both cards' connection lists at load time. The 25k cards.jsonl is never mutated on disk — the
    edges live in their own small overlay so they survive any regeneration of the reference cards.
    0-FP: each bridge is an exact-subject match (an element or crop the Bible also names)."""
    if not overlay.exists():
        return
    for line in overlay.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            e = json.loads(line)
        except json.JSONDecodeError:
            continue
        a, b = e.get("a"), e.get("b")
        rel = e.get("relationship") or "names_the_created_thing"
        ev = e.get("evidence") or ""
        ca, cb = cards.get(a), cards.get(b)
        if not ca or not cb:
            continue
        # hierarchical edges are DIRECTIONAL — the reciprocal carries the inverse label so the floor
        # can be walked as a tree (up = member_of/part_of/…, down = has_member/has_part/…). Lateral
        # edges (shares_scripture, same_family, names_the_created_thing) stay symmetric.
        rev = _INVERSE_REL.get(rel, rel)
        for src, dst, r in ((ca, b, rel), (cb, a, rev)):
            links = src.setdefault("connections", [])
            if not any(isinstance(x, dict) and x.get("to_card_id") == dst for x in links):
                links.append({"to_card_id": dst, "relationship": r, "evidence": ev})


def add_to_default(card: dict) -> None:
    """Add one card to the live default corpus if it is already built (best-effort)."""
    if _DEFAULT is not None:
        _DEFAULT.add_card(card)


def default_corpus(path: Optional[Path] = None) -> Corpus:
    global _DEFAULT
    if _DEFAULT is None:  # double-checked lock: build once, even under concurrent first-hits
        with _DEFAULT_LOCK:
            if _DEFAULT is None:
                df: Dict[str, int] = {}
                _DEFAULT = Corpus(load_cards(path, _df_out=df), df_extra=df)
    return _DEFAULT


def subject_of(query: str) -> Optional[str]:
    """The single word this asking is ABOUT — the globally rarest content token — or None.

    The same computation the merge partition in search() already performs, exposed so a CALLER
    can hold results to it. Needed because a scoped search cannot see its own blindness: within a
    deck whose shelves never contain "wesleyan", the local IDF has no such token, the partition
    falls back to the next-best word ("church"), and six confession cards about the church in
    general come back looking relevant. Only the GLOBAL corpus knows what the question was about;
    this hands that knowledge to the routing layer that chose the scope.
    """
    from .corpus_db import _STOP
    toks = {t for t in _tokens(query) if t not in _STOP}
    if not toks:
        return None
    c = default_corpus()
    return c._subject_of(toks, c._idf(toks))


def search(query: str, limit: int = 25, include_witness: bool = True,
           shelves: Optional[set] = None) -> List[dict]:
    """Ranked search over the default corpus (cards.jsonl) — the floor's retrieval primitive.
    The keeping is shared across both surfaces by default (the .com includes the religious
    cards too); pass include_witness=False for an optional secular-only view. `shelves` scopes
    the search to a deck (the Hare fast-path).

    When shelves are FROZEN (riding the shards), their resident stubs only match on title —
    so the shard FTS (which indexes the full text) fills the remaining slots, and any stub
    that made the cut is rehydrated. The reader never sees a lighter answer because the
    shelf rode the shard."""
    corpus = default_corpus()
    out = corpus.search(query, limit, include_witness, shelves)
    frozen = frozen_shelves()
    if frozen and (shelves is None or (set(shelves) & frozen)) and len(out) < limit:
        from . import corpus_db
        corpus_db.thaw_for(*frozen)
        have = {c.get("id") for c in out}

        # THE SUBJECT PARTITION MUST HOLD ON BOTH SIDES OF THE MERGE, and I learned that the hard
        # way twice in one day. The resident ranker got the partition and the live wire STILL
        # answered "Wesleyan Church" with a Kensington church directory and "The war of Antichrist"
        # at positions 4-8 — because those shelves are frozen, so their hits arrive from the shard's
        # bm25 and never met the rule. Exactly the shape of the stopword bug this afternoon: two
        # matchers, one fixed, the reader unchanged.
        #
        # The shard cannot apply this itself (FTS5 ranks inside SQLite), so the gate goes HERE, at
        # the one point every frozen hit must pass through. Cheap: one token test per candidate.
        from .corpus_db import _STOP          # the one list every matcher uses
        q_tokens = {t for t in _tokens(query) if t not in _STOP}
        subject = corpus._subject_of(q_tokens, corpus._idf(q_tokens)) if q_tokens else None

        for hit in corpus_db.search(query, limit=limit * 3, include_witness=include_witness):
            if (hit.get("shelf") not in frozen or hit.get("id") in have
                    or (shelves is not None and hit.get("shelf") not in shelves)
                    or not is_public(hit)):
                continue        # resident shelves are already fully scored — merge only frozen freight
            if subject and not (Corpus.subject_family(subject) & set(_tokens(_card_text(hit)))):
                continue        # lacks what the question is about — the same partition, same rule
            out.append(hit)
            have.add(hit.get("id"))
            if len(out) >= limit:
                break
    return [rehydrate(c) for c in out]


# ── Library primitives (ported from 1.0's card tools, over the same corpus) ──────────────

def _brief(c: dict) -> Dict[str, Any]:
    return {"id": c.get("id"), "title": c.get("title"), "shelf": c.get("shelf"),
            "surface": c.get("surface"), "snippet": (c.get("body", "") or "")[:200]}


def get_card(card_id: str) -> Optional[dict]:
    """Fetch one PUBLIC card (the full record) by id, or None. Non-public cards
    (private / public_review / archived / quarantine / retracted) are never returned —
    this is the boundary render_card_html and /card rely on."""
    c = default_corpus().cards.get((card_id or "").strip())
    return rehydrate(c) if (c is not None and is_public(c)) else None


def browse(shelf: Optional[str] = None, limit: int = 20, offset: int = 0) -> Dict[str, Any]:
    """Paginated browse over the keeping, optionally filtered to a shelf. Returns briefs."""
    cards = [c for c in default_corpus().cards.values() if is_public(c)]
    if shelf:
        cards = [c for c in cards if (c.get("shelf") or "").lower() == shelf.lower()]
    cards.sort(key=lambda c: ((c.get("shelf") or ""), (c.get("title") or c.get("id") or "")))
    total = len(cards)
    offset = max(0, offset)
    limit = max(1, min(limit, 100))
    return {"total": total, "offset": offset, "limit": limit,
            "shelf": shelf, "cards": [_brief(rehydrate(c)) for c in cards[offset:offset + limit]]}


def stats() -> Dict[str, Any]:
    """Counts over the keeping — total, by shelf, by surface."""
    from collections import Counter
    cards = [c for c in default_corpus().cards.values() if is_public(c)]
    out = {"total": len(cards),
           # EVERY shelf, not the largest 40. This was `most_common(40)`, and the library's browse
           # dropdown is built from it — so 63 of 103 shelves could not be reached by browsing at
           # all, while /cards?shelf=X served them perfectly well. A cap that hides two-thirds of
           # the keeping from the one control meant for reaching it is a silent truncation, and it
           # reads to a visitor as "this is all there is".
           "by_shelf": dict(Counter((c.get("shelf") or "?") for c in cards).most_common()),
           "by_surface": dict(Counter((c.get("surface") or "?") for c in cards))}
    fz = frozen_shelves()
    if fz:
        # named, never silent: these shelves are resident as stubs (graph + titles), full
        # bodies riding the SQLite shards and rehydrated on read
        out["frozen_shelves"] = sorted(fz)
    return out


def daily(seed: Optional[str] = None) -> Optional[dict]:
    """A deterministic 'card of the day' — same card all day, different each day. Stable: the
    seed (default today's UTC date) hashes to an index, so it needs no stored state."""
    import hashlib
    import time as _time
    ids = sorted(cid for cid, c in default_corpus().cards.items() if is_public(c))
    if not ids:
        return None
    if seed is None:
        seed = _time.strftime("%Y-%m-%d", _time.gmtime())
    idx = int(hashlib.sha256(seed.encode("utf-8")).hexdigest(), 16) % len(ids)
    return rehydrate(default_corpus().cards[ids[idx]])


def connections(card_id: str, limit: int = 10) -> Optional[Dict[str, Any]]:
    """Cards related to one card — its explicit links plus same-shelf siblings. None if absent."""
    c = get_card(card_id)
    if c is None:
        return None
    shelf = c.get("shelf")
    sibs = [_brief(x) for x in default_corpus().cards.values()
            if x.get("id") != card_id and x.get("shelf") == shelf and is_public(x)][:max(1, min(limit, 50))]
    links = c.get("links") or c.get("connections") or c.get("refs") or []
    return {"id": card_id, "shelf": shelf, "links": links, "same_shelf": sibs}


def locate(q: str, limit: int = 5) -> Dict[str, Any]:
    """Find the card for a query: exact id, then title match, else fall back to ranked search."""
    # found: "q or ''" only substitutes the fallback for a FALSY q — a truthy non-string (an
    # int from an uncoerced MCP tool call arg) survives past that guard and crashes on
    # ".strip()". Matches corpus.search()'s fix, same module.
    q = (str(q) if q else "").strip()
    if not q:
        return {"query": q, "by": "none", "matches": []}
    cards = default_corpus().cards
    if q in cards and is_public(cards[q]):
        return {"query": q, "by": "id", "matches": [_brief(cards[q])]}
    ql = q.lower()
    title_hits = [_brief(c) for c in cards.values() if is_public(c) and ql in (c.get("title") or "").lower()]
    if title_hits:
        return {"query": q, "by": "title", "matches": title_hits[:limit]}
    return {"query": q, "by": "search", "matches": [_brief(c) for c in search(q, limit=limit)]}


def health() -> Dict[str, Any]:
    """Corpus health — is the keeping loaded and sound."""
    cards = [c for c in default_corpus().cards.values() if is_public(c)]
    n = len(cards)
    return {"ok": n > 0, "total": n,
            "with_body": sum(1 for c in cards if (c.get("body") or "").strip()),
            "shelves": len({c.get("shelf") for c in cards}),
            "surfaces": sorted({(c.get("surface") or "?") for c in cards})}


def gauges() -> Dict[str, Any]:
    """THE GAUGE PANEL — every invented ranking constant, located on the measured curve.

    Matt, 2026-08-02: *"Rate functions relate to the total amount collected... All of this is
    Math. We should be building formulas and verifiers that meet each need."* — and the same day
    the first measurement through this lens found `min_idf = 1.5` admitting 100.0% of 300,463
    tokens: a distinctiveness floor tuned when the corpus was small, gone silently vacuous as it
    grew. A constant is a promise about a distribution; when the distribution moves, the promise
    rots unless something re-measures it. This does, from the live index, every time it is asked.

    Verdicts are three-state and blunt: VACUOUS (the constant excludes almost nothing — dead
    weight wearing a guard's uniform), BINDING (doing real work), or the number speaks for
    itself. It FLAGS; it never auto-tunes — re-deriving a ranking constant is a change to what
    every reader sees and goes through the gate with a before/after probe battery, not through a
    monitor. Every figure carries its means, per the coverage rule.
    """
    import math as _math
    c = default_corpus()
    dfs = sorted((len(v) + c._df_extra.get(k, 0) for k, v in c._by_token.items()),
                 reverse=True)
    n_tokens = len(dfs)
    n_cards = c._n

    # the Zipf fit — the constant-ratio growth law the whole index rides on
    lo, hi = 10, min(10001, n_tokens)
    pts = [( _math.log(r), _math.log(dfs[r - 1])) for r in range(lo, hi) if dfs[r - 1] > 0]
    slope = r2 = None
    if len(pts) > 100:
        mx = sum(p[0] for p in pts) / len(pts)
        my = sum(p[1] for p in pts) / len(pts)
        denom = sum((x - mx) ** 2 for x, _ in pts)
        if denom > 0:
            slope = sum((x - mx) * (y - my) for x, y in pts) / denom
            ss_res = sum((y - (my + slope * (x - mx))) ** 2 for x, y in pts)
            ss_tot = sum((y - my) ** 2 for _, y in pts) or 1.0
            r2 = 1 - ss_res / ss_tot

    # min_idf on the curve: what fraction of the vocabulary does the floor actually admit?
    cut_df = n_cards / _math.exp(self_min := c.min_idf)
    admitted = sum(1 for d in dfs if d < cut_df)
    admit_frac = admitted / n_tokens if n_tokens else 0.0

    # the candidate cap: how many tokens could flood it (the starvation class of bug)
    flood = sum(1 for d in dfs if d > 600)

    return {
        "zipf": {"slope": round(slope, 3) if slope is not None else None,
                 "r2": round(r2, 4) if r2 is not None else None,
                 "means": f"log-log fit over ranks {lo}-{hi - 1} of {n_tokens:,} tokens"},
        "min_idf": {"value": self_min, "admits_fraction": round(admit_frac, 4),
                    "verdict": ("VACUOUS" if admit_frac > 0.99
                                else "BINDING" if admit_frac < 0.90 else "MARGINAL"),
                    "means": f"tokens with df < {int(cut_df):,} of {n_cards:,} cards"},
        "candidate_cap": {"value": 600, "tokens_that_flood": flood,
                          "means": "tokens with df > cap; rarest-first seeding makes the cap "
                                   "safe, this counts how often it is exercised"},
        "subject_tier": {"value": SUBJECT_TIER,
                         "max_idf": round(max((_math.log(n_cards / (d + 1)) for d in dfs[-1:]),
                                              default=0.0), 2),
                         "means": "the tier must exceed any reachable tf-idf sum; max single-"
                                  "token idf shown for scale"},
        "population": {"tokens": n_tokens, "cards": n_cards},
    }
