"""Corpus ranker — IDF inverted-index retrieval over the keeping (floor primitive #7).

The same distinctiveness-floored IDF ranker as 1.0 (api/cards.py): a card surfaces only
if it matches a genuinely DISTINCTIVE query token, so common words don't drag in
off-topic cards. Surface-filtered: the secular reach (.com) sees only secular-tagged
cards; the witness surface (.org) sees the whole keeping. The corpus is loaded from
cards.jsonl (data, gitignored — generated by tools/migrate_cards.py).

The 1.0 authority-tier boost (scripture/creed/... rank higher) is intentionally omitted
from the secular core — it is witness-surface ranking and belongs with the .org overlay.
"""
from __future__ import annotations

import json
import math
import os
import re
from pathlib import Path
from typing import Dict, List, Optional

# A query token must be at least this distinctive (high IDF) to count as a real hit.
# Tuned for a large corpus; lower it for small fixtures.
MIN_DISTINCTIVE_IDF = 1.5

_FIELDS = ("title", "body", "bands", "source")


def _tokens(text: str) -> List[str]:
    return re.findall(r"[a-zA-Z][a-zA-Z']{1,}", (text or "").lower())


def _card_text(card: dict) -> str:
    src = card.get("source") or {}
    return " ".join([
        card.get("title", ""),
        (card.get("body", "") or "")[:1000],
        " ".join(card.get("bands") or []),
        src.get("ref", ""),
        src.get("label", ""),
    ]).lower()


class Corpus:
    """An indexed, searchable set of cards (id -> card dict)."""

    def __init__(self, cards: Dict[str, dict], min_idf: float = MIN_DISTINCTIVE_IDF):
        self.cards = cards
        self.min_idf = min_idf
        self._by_token: Dict[str, List[str]] = {}
        for cid, c in cards.items():
            if c.get("retracted") or c.get("lifecycle_stage") in ("archived", "quarantine"):
                continue
            for t in set(_tokens(_card_text(c))):
                self._by_token.setdefault(t, []).append(cid)
        self._n = max(1, len(self._index_card_ids()))

    def _index_card_ids(self) -> set:
        ids: set = set()
        for cids in self._by_token.values():
            ids.update(cids)
        return ids

    def _idf(self, query_tokens: set) -> Dict[str, float]:
        return {t: max(0.0, math.log(self._n / (len(self._by_token.get(t, ())) + 1)))
                for t in query_tokens}

    def _candidates(self, query_tokens: set, max_candidates: int = 600) -> List[str]:
        counts: Dict[str, int] = {}
        for qt in query_tokens:
            for cid in self._by_token.get(qt, []):
                counts[cid] = counts.get(cid, 0) + 1
        return sorted(counts, key=lambda x: -counts[x])[:max_candidates]

    def _score(self, card: dict, query_tokens: set, idf: Dict[str, float]) -> float:
        doc_tokens = _tokens(_card_text(card))
        if not doc_tokens:
            return 0.0
        common = query_tokens & set(doc_tokens)
        if not common:
            return 0.0
        if max((idf.get(t, 0.0) for t in common), default=0.0) < self.min_idf:
            return 0.0
        counts = {t: 0 for t in common}
        for t in doc_tokens:
            if t in counts:
                counts[t] += 1
        score = sum(counts[t] * idf.get(t, 0.0) for t in common) / math.log(len(doc_tokens) + 10)
        if len(common) == len(query_tokens):
            score *= 1.5
        return float(score)

    def search(self, query: str, limit: int = 25, surface: str = "secular") -> List[dict]:
        """Ranked search. surface="secular" returns only secular cards; "witness" returns all."""
        query_tokens = set(_tokens(query or ""))
        if not query_tokens:
            return []
        idf = self._idf(query_tokens)
        scored = []
        for cid in self._candidates(query_tokens):
            c = self.cards.get(cid)
            if not c or c.get("retracted"):
                continue
            if c.get("lifecycle_stage") in ("archived", "quarantine"):
                continue
            if surface == "secular" and c.get("surface") != "secular":
                continue
            s = self._score(c, query_tokens, idf)
            if s > 0:
                scored.append((s, c))
        scored.sort(key=lambda x: -x[0])
        return [c for _s, c in scored[:max(1, int(limit))]]


# ── module-level default corpus (lazy, from cards.jsonl) ─────────────────

_DEFAULT: Optional[Corpus] = None


def _cards_path() -> Path:
    env = os.environ.get("CONCORDANCE_CARDS_JSONL", "").strip()
    if env:
        return Path(env)
    data = os.environ.get("CONCORDANCE_DATA_DIR", "").strip()
    return (Path(data) if data else Path("data")) / "cards.jsonl"


def load_cards(path: Optional[Path] = None) -> Dict[str, dict]:
    """Load cards from a JSONL file into an id -> card dict. Empty if absent."""
    p = path or _cards_path()
    out: Dict[str, dict] = {}
    if not p.exists():
        return out
    with open(p, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                c = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(c, dict) and c.get("id"):
                out[c["id"]] = c
    return out


def default_corpus(path: Optional[Path] = None) -> Corpus:
    global _DEFAULT
    if _DEFAULT is None:
        _DEFAULT = Corpus(load_cards(path))
    return _DEFAULT


def search(query: str, limit: int = 25, surface: str = "secular") -> List[dict]:
    """Ranked search over the default corpus (cards.jsonl). The floor's retrieval primitive."""
    return default_corpus().search(query, limit, surface)
