"""Corpus ranker — IDF inverted-index retrieval over the keeping (floor primitive #7).

The same distinctiveness-floored IDF ranker as 1.0 (api/cards.py): a card surfaces only
if it matches a genuinely DISTINCTIVE query token, so common words don't drag in
off-topic cards. Surface-filtered: the secular reach (.com) sees only secular-tagged
cards; the witness surface (.org) sees the whole keeping. The corpus is loaded from
cards.jsonl (data, gitignored — generated by tools/migrate_cards.py).

The 1.0 authority-tier boost (scripture/creed/... rank higher) is intentionally omitted
from the secular core — it is witness-surface ranking and belongs with the .org overlay.
"""
from __future__ import annotations

import json
import math
import os
import re
import threading
from pathlib import Path
from typing import Any, Dict, List, Optional

# A query token must be at least this distinctive (high IDF) to count as a real hit.
# Tuned for a large corpus; lower it for small fixtures.
MIN_DISTINCTIVE_IDF = 1.5

_FIELDS = ("title", "body", "bands", "source")


def _tokens(text: str) -> List[str]:
    return re.findall(r"[a-zA-Z][a-zA-Z']{1,}", (text or "").lower())


def _card_text(card: dict) -> str:
    src = card.get("source") or {}
    return " ".join([
        card.get("title", ""),
        (card.get("body", "") or "")[:1000],
        " ".join(card.get("bands") or []),
        src.get("ref", ""),
        src.get("label", ""),
    ]).lower()


PUBLIC_STAGES = frozenset({"public", "featured"})


def is_public(card: dict) -> bool:
    """True iff a card may appear on ANY public read path — an ALLOWLIST, not a denylist.
    ONE source of truth (graph.py imports this too, so the two can never diverge): every
    stage except public/featured — private, public_review, archived, quarantine, retracted —
    is withheld. A denylist here (archived/quarantine only) is exactly what leaked the
    operator's private cards onto the public surface."""
    if not isinstance(card, dict) or card.get("retracted"):
        return False
    return (card.get("lifecycle_stage") or "public") in PUBLIC_STAGES


class Corpus:
    """An indexed, searchable set of cards (id -> card dict)."""

    def __init__(self, cards: Dict[str, dict], min_idf: float = MIN_DISTINCTIVE_IDF):
        self.cards = cards
        self.min_idf = min_idf
        self._by_token: Dict[str, List[str]] = {}
        for cid, c in cards.items():
            if not is_public(c):
                continue
            for t in set(_tokens(_card_text(c))):
                self._by_token.setdefault(t, []).append(cid)
        self._n = max(1, len(self._index_card_ids()))

    def add_card(self, card: dict) -> None:
        """Insert one card into the live corpus AND its token index — so a just-minted
        verification is searchable immediately, no restart. Idempotent by id."""
        cid = card.get("id")
        if not cid:
            return
        self.cards[cid] = card
        if is_public(card):
            for t in set(_tokens(_card_text(card))):
                self._by_token.setdefault(t, [])
                if cid not in self._by_token[t]:
                    self._by_token[t].append(cid)
            self._n = max(1, len(self._index_card_ids()))

    def _index_card_ids(self) -> set:
        ids: set = set()
        for cids in self._by_token.values():
            ids.update(cids)
        return ids

    def _idf(self, query_tokens: set) -> Dict[str, float]:
        return {t: max(0.0, math.log(self._n / (len(self._by_token.get(t, ())) + 1)))
                for t in query_tokens}

    def _candidates(self, query_tokens: set, max_candidates: int = 600) -> List[str]:
        counts: Dict[str, int] = {}
        for qt in query_tokens:
            for cid in self._by_token.get(qt, []):
                counts[cid] = counts.get(cid, 0) + 1
        return sorted(counts, key=lambda x: -counts[x])[:max_candidates]

    def _score(self, card: dict, query_tokens: set, idf: Dict[str, float]) -> float:
        doc_tokens = _tokens(_card_text(card))
        if not doc_tokens:
            return 0.0
        common = query_tokens & set(doc_tokens)
        if not common:
            return 0.0
        if max((idf.get(t, 0.0) for t in common), default=0.0) < self.min_idf:
            return 0.0
        counts = {t: 0 for t in common}
        for t in doc_tokens:
            if t in counts:
                counts[t] += 1
        score = sum(counts[t] * idf.get(t, 0.0) for t in common) / math.log(len(doc_tokens) + 10)
        if len(common) == len(query_tokens):
            score *= 1.5
        return float(score)

    def search(self, query: str, limit: int = 25, include_witness: bool = True) -> List[dict]:
        """Ranked search over the keeping.

        The keeping is ONE SHARED library: by default BOTH surfaces draw the whole thing
        — the .com includes the religious cards too (Matt, 2026-06-26: "the religious
        cards can be included"; "we are not hiding anything"). `include_witness=False`
        gives an optional scrubbed view if a caller ever wants secular-only results."""
        query_tokens = set(_tokens(query or ""))
        if not query_tokens:
            return []
        idf = self._idf(query_tokens)
        # exact-match targets: the query as typed, and its canonical verse forms — so a verse
        # lookup ("Philippians 4:13", the most common human search) ranks the verse card first
        # instead of a fuzzy book match. Reuses the growth engine's one verse canonicalizer.
        from . import growth as _growth
        qn = " ".join((query or "").lower().split())
        q_exact = {qn} | {r.lower() for r in _growth.refs_in_text(query or "")}
        scored = []
        for cid in self._candidates(query_tokens):
            c = self.cards.get(cid)
            if not c or not is_public(c):
                continue
            if not include_witness and c.get("surface") == "witness":
                continue
            s = self._score(c, query_tokens, idf)
            if s > 0:
                title_n = " ".join(str(c.get("title", "")).lower().split())
                ref_n = " ".join(str((c.get("source") or {}).get("ref", "")).lower().split())
                if title_n in q_exact or (ref_n and ref_n in q_exact and title_n in q_exact):
                    s *= 9.0                              # THE card for this exact reference/title
                elif q_exact and (title_n in q_exact or ref_n in q_exact):
                    s *= 4.0
                scored.append((s, c))
        scored.sort(key=lambda x: -x[0])
        return [c for _s, c in scored[:max(1, int(limit))]]


# ── module-level default corpus (lazy, from cards.jsonl) ─────────────────

_DEFAULT: Optional[Corpus] = None
_DEFAULT_LOCK = threading.Lock()


def _cards_path() -> Path:
    env = os.environ.get("CONCORDANCE_CARDS_JSONL", "").strip()
    if env:
        return Path(env)
    data = os.environ.get("CONCORDANCE_DATA_DIR", "").strip()
    return (Path(data) if data else Path("data")) / "cards.jsonl"


def load_cards(path: Optional[Path] = None) -> Dict[str, dict]:
    """Load cards from a JSONL file into an id -> card dict. Empty if absent."""
    p = path or _cards_path()
    out: Dict[str, dict] = {}
    if not p.exists():
        return out
    with open(p, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                c = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(c, dict) and c.get("id"):
                out[c["id"]] = c
    # further sources that join the SAME graph as Scripture and the tradition:
    #   verified_cards.jsonl — minted live from sealed verifications (data-only, gitignored)
    #   reference_cards.jsonl — the deep reference work already in the verifiers (periodic table,
    #                           physical constants, …), carded and GIT-TRACKED so the content is
    #                           on github, not only in the code
    if path is None:
        for extra in ("verified_cards.jsonl", "reference_cards.jsonl", "keystone_seeds.jsonl"):
            xp = p.parent / extra
            if not xp.exists():
                continue
            with open(xp, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        c = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if isinstance(c, dict) and c.get("id"):
                        out[c["id"]] = c
        for overlay in ("reference_bridges.jsonl", "keystone_bridges.jsonl"):
            _apply_bridges(out, p.parent / overlay)
    return out


def _apply_bridges(cards: Dict[str, dict], overlay: Path) -> None:
    """Graft the two trees: apply the git-tracked reference→Scripture bridges reciprocally onto
    both cards' connection lists at load time. The 25k cards.jsonl is never mutated on disk — the
    edges live in their own small overlay so they survive any regeneration of the reference cards.
    0-FP: each bridge is an exact-subject match (an element or crop the Bible also names)."""
    if not overlay.exists():
        return
    for line in overlay.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            e = json.loads(line)
        except json.JSONDecodeError:
            continue
        a, b = e.get("a"), e.get("b")
        rel = e.get("relationship") or "names_the_created_thing"
        ev = e.get("evidence") or ""
        ca, cb = cards.get(a), cards.get(b)
        if not ca or not cb:
            continue
        for src, dst in ((ca, b), (cb, a)):
            links = src.setdefault("connections", [])
            if not any(isinstance(x, dict) and x.get("to_card_id") == dst for x in links):
                links.append({"to_card_id": dst, "relationship": rel, "evidence": ev})


def add_to_default(card: dict) -> None:
    """Add one card to the live default corpus if it is already built (best-effort)."""
    if _DEFAULT is not None:
        _DEFAULT.add_card(card)


def default_corpus(path: Optional[Path] = None) -> Corpus:
    global _DEFAULT
    if _DEFAULT is None:  # double-checked lock: build once, even under concurrent first-hits
        with _DEFAULT_LOCK:
            if _DEFAULT is None:
                _DEFAULT = Corpus(load_cards(path))
    return _DEFAULT


def search(query: str, limit: int = 25, include_witness: bool = True) -> List[dict]:
    """Ranked search over the default corpus (cards.jsonl) — the floor's retrieval primitive.
    The keeping is shared across both surfaces by default (the .com includes the religious
    cards too); pass include_witness=False for an optional secular-only view."""
    return default_corpus().search(query, limit, include_witness)


# ── Library primitives (ported from 1.0's card tools, over the same corpus) ──────────────

def _brief(c: dict) -> Dict[str, Any]:
    return {"id": c.get("id"), "title": c.get("title"), "shelf": c.get("shelf"),
            "surface": c.get("surface"), "snippet": (c.get("body", "") or "")[:200]}


def get_card(card_id: str) -> Optional[dict]:
    """Fetch one PUBLIC card (the full record) by id, or None. Non-public cards
    (private / public_review / archived / quarantine / retracted) are never returned —
    this is the boundary render_card_html and /card rely on."""
    c = default_corpus().cards.get((card_id or "").strip())
    return c if (c is not None and is_public(c)) else None


def browse(shelf: Optional[str] = None, limit: int = 20, offset: int = 0) -> Dict[str, Any]:
    """Paginated browse over the keeping, optionally filtered to a shelf. Returns briefs."""
    cards = [c for c in default_corpus().cards.values() if is_public(c)]
    if shelf:
        cards = [c for c in cards if (c.get("shelf") or "").lower() == shelf.lower()]
    cards.sort(key=lambda c: ((c.get("shelf") or ""), (c.get("title") or c.get("id") or "")))
    total = len(cards)
    offset = max(0, offset)
    limit = max(1, min(limit, 100))
    return {"total": total, "offset": offset, "limit": limit,
            "shelf": shelf, "cards": [_brief(c) for c in cards[offset:offset + limit]]}


def stats() -> Dict[str, Any]:
    """Counts over the keeping — total, by shelf, by surface."""
    from collections import Counter
    cards = [c for c in default_corpus().cards.values() if is_public(c)]
    return {"total": len(cards),
            "by_shelf": dict(Counter((c.get("shelf") or "?") for c in cards).most_common(40)),
            "by_surface": dict(Counter((c.get("surface") or "?") for c in cards))}


def daily(seed: Optional[str] = None) -> Optional[dict]:
    """A deterministic 'card of the day' — same card all day, different each day. Stable: the
    seed (default today's UTC date) hashes to an index, so it needs no stored state."""
    import hashlib
    import time as _time
    ids = sorted(cid for cid, c in default_corpus().cards.items() if is_public(c))
    if not ids:
        return None
    if seed is None:
        seed = _time.strftime("%Y-%m-%d", _time.gmtime())
    idx = int(hashlib.sha256(seed.encode("utf-8")).hexdigest(), 16) % len(ids)
    return default_corpus().cards[ids[idx]]


def connections(card_id: str, limit: int = 10) -> Optional[Dict[str, Any]]:
    """Cards related to one card — its explicit links plus same-shelf siblings. None if absent."""
    c = get_card(card_id)
    if c is None:
        return None
    shelf = c.get("shelf")
    sibs = [_brief(x) for x in default_corpus().cards.values()
            if x.get("id") != card_id and x.get("shelf") == shelf and is_public(x)][:max(1, min(limit, 50))]
    links = c.get("links") or c.get("connections") or c.get("refs") or []
    return {"id": card_id, "shelf": shelf, "links": links, "same_shelf": sibs}


def locate(q: str, limit: int = 5) -> Dict[str, Any]:
    """Find the card for a query: exact id, then title match, else fall back to ranked search."""
    q = (q or "").strip()
    if not q:
        return {"query": q, "by": "none", "matches": []}
    cards = default_corpus().cards
    if q in cards and is_public(cards[q]):
        return {"query": q, "by": "id", "matches": [_brief(cards[q])]}
    ql = q.lower()
    title_hits = [_brief(c) for c in cards.values() if is_public(c) and ql in (c.get("title") or "").lower()]
    if title_hits:
        return {"query": q, "by": "title", "matches": title_hits[:limit]}
    return {"query": q, "by": "search", "matches": [_brief(c) for c in search(q, limit=limit)]}


def health() -> Dict[str, Any]:
    """Corpus health — is the keeping loaded and sound."""
    cards = [c for c in default_corpus().cards.values() if is_public(c)]
    n = len(cards)
    return {"ok": n > 0, "total": n,
            "with_body": sum(1 for c in cards if (c.get("body") or "").strip()),
            "shelves": len({c.get("shelf") for c in cards}),
            "surfaces": sorted({(c.get("surface") or "?") for c in cards})}
