"""Test-wide guards.

The tortoise (find.py) reaches the open web only in production. Tests must NEVER touch the network,
so web-find is disabled here by default. test_find re-enables it per-test with STUBBED providers
(never real HTTP) and restores this default afterward.
"""
import os
from pathlib import Path

import pytest

os.environ["WEB_FIND_DISABLED"] = "1"

# The computer_science verifier RUNS submitted code — its whole purpose. After the RCE fix (713de33)
# that execution is refused unless CONCORDANCE_ALLOW_CODE_EXEC=1, so an anonymous caller on the
# public box can never reach it. The test suite is a controlled environment running only its own
# fixtures, so it opts in here to exercise the real code-runner (the FP gate, alias parity, and the
# code-correctness reasoning test all depend on it). Production never loads conftest.py, so this
# does NOT weaken the secure default — test_review_fixes.py::test_..._refuses_code_exec_by_default
# clears the var and proves the refusal still holds.
os.environ["CONCORDANCE_ALLOW_CODE_EXEC"] = "1"

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def data_present(*rel: str) -> bool:
    """True when every named path under data/ exists. The keeping (`cards.jsonl`) and its shelves
    (`strongs/`, `characters/`, `commentary/`, the WEB Bible, the shards) are gitignored and
    generated by tools/migrate_*.py, so on a CLEAN CLONE they are absent while the tracked seed
    files are present."""
    return all((DATA / r).exists() for r in rel)


# Files whose tests need the generated keeping/shelves (gitignored, built by tools/migrate_*.py).
# On a CLEAN CLONE those are absent, so these files SKIP WITH A STATED REASON a stranger can read;
# on the box (data present) they run. VERIFIED 2026-08-26: with the corpus present each of these
# passes — so the clean-clone failure was corpus-only, not a masked bug. A file that fails WITH the
# corpus is a real red and is NOT listed here (it is fixed, never skipped — see test_site/test_present).
_CORPUS_DEPENDENT = {
    "test_apothecary": ("cards.jsonl", "the apothecary shelf"),
    "test_ask": ("bible_en.jsonl", "the WEB Bible and keeping"),
    "test_backmatter": ("bible_en.jsonl", "Bible references and the lexicon"),
    "test_bible_places": ("bible_en.jsonl", "the WEB Bible and places"),
    "test_community": ("cards.jsonl", "member shelves in the keeping"),
    "test_encyclopedia_and_voices": ("characters", "the characters/encyclopedia shelf"),
    "test_harmony": ("bible_en.jsonl", "verbatim gospel text"),
    "test_last_mile": ("bible_en.jsonl", "the Bible book index"),
    "test_mcp_gate": ("cards.jsonl", "the keeping the gate serves"),
    "test_narratives": ("bible_en.jsonl", "storyboard scripture references"),
    "test_nothing_is_isolated": ("cards.jsonl", "the keeping graph"),
    "test_null_assay": ("cards.jsonl", "the keeping"),
    "test_reachable_from_the_floor": ("cards.jsonl", "the floor in the keeping"),
    "test_seekers": ("bible_en.jsonl", "references and the keeping"),
    "test_timeline": ("bible_en.jsonl", "verbatim chapter text"),
    "test_understanding": ("cards.jsonl", "the field library"),
    "test_wayfind": ("cards.jsonl", "the keeping"),
}


def pytest_collection_modifyitems(config, items):
    """Skip corpus-dependent files with a stated reason when their data is absent (a clean clone),
    so `tools/check.py` on a clean clone reports readable skips, not reds a stranger must decode. On
    the box the corpus is present and they run. See _CORPUS_DEPENDENT and its verification note."""
    for item in items:
        stem = item.path.stem if hasattr(item, "path") else Path(str(item.fspath)).stem
        req = _CORPUS_DEPENDENT.get(stem)
        if req and not data_present(req[0]):
            item.add_marker(pytest.mark.skip(
                reason=("corpus not provisioned (%s): %s absent — generate with tools/migrate_*.py"
                        % (req[1], req[0]))))


_REAL_CARDS: dict = {}
_REAL_CORPUS = None


def real_cards() -> dict:
    """The REAL keeping, for the few tests whose whole point is to measure it.

    WHY THIS EXISTS. 53 test modules open with a line like

        os.environ["CONCORDANCE_DATA_DIR"] = tempfile.mkdtemp(...)

    which is right for them — they want a scratch corpus to write into. But the variable is
    process-wide and corpus.default_corpus() is memoized on first touch, so WHICH corpus the
    singleton ends up holding is settled by a race between module imports and the first read.

    MEASURED 2026-08-03 with tools/vacuity_plugin.py across the whole suite: in a FULL run the
    singleton holds the real keeping. 182 tests called default_corpus() and not one received an
    empty corpus; 155 saw more than 100k cards. The gate is NOT reading an empty library. An
    earlier draft of this docstring asserted that it was, from a subset run — that was wrong, and
    the correction is recorded here rather than quietly deleted.

    The race is real in SUBSET runs, which is how anyone actually develops:

        pytest tests/test_floor.py tests/test_reachable_from_the_floor.py

    collects a hijacking module early, its temp dir wins, and the corpus is empty. A file whose
    whole claim is about the keeping then iterates zero cards and passes. Not hypothetical: it is
    exactly how the missing teardown in tests/test_floor.py stayed invisible. Run alone the
    reachability file passed; run in that pair it failed; which answer you got depended on your
    command line, and neither answer announced which corpus it had measured.

    So the few files whose verdict IS the keeping load the real cards here instead of inheriting
    the race, and assert on the count they got. Their answer must not depend on what else
    happened to be collected.
    """
    global _REAL_CARDS
    if not _REAL_CARDS:
        from concordance import corpus
        # Reuse the singleton's cards when it already holds the real keeping (same guard and
        # same reasoning as real_corpus_object below): under the full gate this makes the cost
        # of the honest walk ZERO extra loads instead of a duplicate 548k-card read. The
        # singleton may carry a handful of cards sibling tests minted in-process; those are
        # nested by construction, and the walk measuring "files + what this run minted" is the
        # same coverage the vacuity audit already reports.
        existing = corpus._DEFAULT
        if existing is not None and len(getattr(existing, "cards", {}) or {}) > 100_000:
            _REAL_CARDS = existing.cards
            return _REAL_CARDS
        prior = os.environ.get("CONCORDANCE_DATA_DIR")
        os.environ["CONCORDANCE_DATA_DIR"] = str(ROOT / "data")
        try:
            _REAL_CARDS = corpus.load_cards()      # no path: also pulls the sibling card sources
        finally:
            if prior is None:
                os.environ.pop("CONCORDANCE_DATA_DIR", None)
            else:
                os.environ["CONCORDANCE_DATA_DIR"] = prior
    return _REAL_CARDS


def real_corpus_object():
    """A Corpus over the real cards, built once, THE SAME WAY default_corpus() builds it.

    The df_extra argument is not optional decoration. load_cards(_df_out=df) streams each frozen
    card's document frequencies during the read so no per-card token list ever materialises, and
    Corpus(cards, df_extra=df) takes them pre-computed. Building `Corpus(cards)` without it makes
    the index the naive way over 548k cards: the first draft of this helper did exactly that and
    three test files had not finished after nine minutes. Measured, then fixed — a check nobody
    can afford to run is a check that gets deleted.
    """
    global _REAL_CORPUS, _REAL_CARDS
    if _REAL_CORPUS is None:
        from concordance import corpus
        # REUSE THE SINGLETON WHEN IT ALREADY HOLDS THE REAL KEEPING. Under the full gate it does
        # (measured: 182 default_corpus() callers, none empty), and the first version of this
        # helper built a SECOND identical 548k-card corpus beside it anyway. Two corpora in one
        # process on a busy machine meant the end-of-run teardown paged for the better part of an
        # hour — three gate runs in a row looked hung after "[100%]" and two were killed for it.
        # The duplicate corpus was my design error, and this branch is its removal. The
        # independent load below remains for subset runs, where the singleton is a scratch or
        # fixture corpus and reusing it would hand the reachability walk a five-card floor.
        existing = corpus._DEFAULT
        if existing is not None and len(getattr(existing, "cards", {}) or {}) > 100_000:
            _REAL_CORPUS = existing
            if not _REAL_CARDS:
                _REAL_CARDS = existing.cards
            return _REAL_CORPUS
        prior = os.environ.get("CONCORDANCE_DATA_DIR")
        os.environ["CONCORDANCE_DATA_DIR"] = str(ROOT / "data")
        try:
            df: dict = {}
            cards = corpus.load_cards(_df_out=df)
            _REAL_CORPUS = corpus.Corpus(cards, df_extra=df)
            if not _REAL_CARDS:
                _REAL_CARDS = cards            # one read serves both helpers
        finally:
            if prior is None:
                os.environ.pop("CONCORDANCE_DATA_DIR", None)
            else:
                os.environ["CONCORDANCE_DATA_DIR"] = prior
    return _REAL_CORPUS


@pytest.fixture
def real_corpus():
    """Install the REAL keeping as the process corpus for one test, then put back exactly what
    was there.

    For the checks whose whole point is that the library actually answers -- "a how-to question
    reaches the field library", "wayfind stays on topic". Those were written as

        if not corpus.search("survival shelter", limit=1):
            return          # 'positive check guarded on a provisioned corpus'

    which reports a pass without having checked anything. MEASURED 2026-08-03: under the FULL
    gate the corpus is provisioned, so those assertions do run — an earlier claim here that they
    "had never once executed" was wrong and is corrected. What is true is that the guard makes
    them conditional on a race nobody can see: in any subset run the search comes back empty, the
    body is skipped, and the test still reports green.

    Asking for a real corpus outright removes the condition. The check either runs or fails; it
    can no longer half-run and call that success.

    Restores corpus._DEFAULT and graph._GRAPH on the way out, so this fixture cannot become the
    next thing that leaves a global changed behind it.
    """
    from concordance import corpus, graph
    prior_corpus = corpus._DEFAULT
    prior_graph = getattr(graph, "_GRAPH", None)
    corpus._DEFAULT = real_corpus_object()
    graph._GRAPH = None
    try:
        yield corpus._DEFAULT
    finally:
        corpus._DEFAULT = prior_corpus
        graph._GRAPH = prior_graph


@pytest.fixture
def corpus_left_as_found():
    """For tests that REPLACE the corpus singleton with a small fixture of their own.

    Five files assign `corpus._DEFAULT = corpus.Corpus({...})` directly, which is a reasonable way
    to test against a known tiny graph. AUDITED 2026-08-03, and most of them are already correct:

      * test_graph.py, test_privacy.py -- pytest's `teardown_function` hook, which runs after
        every test in the module including on failure. Robust. Left alone.
      * test_corpus_freeze.py, test_wants.py -- restore explicitly. Left alone.
      * test_library.py -- cleans up in a `test_cleanup()` that asserts nothing and relies on
        being defined last. It works today because pytest runs a file in definition order, and it
        breaks silently the day someone appends a test below it.

    A first pass of this audit grepped for `yield|finally|monkeypatch`, saw none of those in
    test_graph/test_privacy, and concluded all three "never put the singleton back". That was
    wrong -- the grep did not know about teardown_function -- and it was written into this
    docstring before being checked. Recorded here because a false accusation in a comment outlives
    the person who made it.

    Ask for this fixture and the restore is automatic, with no ordering assumption.
    """
    from concordance import corpus, graph
    prior_corpus = corpus._DEFAULT
    prior_graph = getattr(graph, "_GRAPH", None)
    try:
        yield
    finally:
        corpus._DEFAULT = prior_corpus
        graph._GRAPH = prior_graph
