#!/usr/bin/env python3
"""WARM THE VOICE — synthesize the kept, repeated lines ONCE, in the operator's own voice.

Matt, 2026-09-22: "turn this into a strength." The ElevenLabs voice is the ceiling; the content-
addressed cache (voice.py, keyed by voice|model|text) means the paid API is touched AT MOST ONCE per
distinct utterance. So the repeated spoken lines — the cube's rules and its Socratic checks, and the
coach's fixed prompts — are the same words for every learner, forever. Voice them once and they
become a KEPT ASSET: instant, free, and (with the service worker) offline, in the operator's voice.

This walks those lines and calls voice.speak on each. A line already in the cache is a HIT and costs
nothing; only a genuinely new line spends. Idempotent, bounded, honest:

    ELEVENLABS_API_KEY=… ELEVENLABS_VOICE_ID=… PYTHONPATH=src python tools/warm_voice.py --dry-run
    …                                          PYTHONPATH=src python tools/warm_voice.py --limit 40
    …                                          PYTHONPATH=src python tools/warm_voice.py           # all

It voices ONLY what the app speaks verbatim (the lesson player's examples + decodable sentences, and
the coach's per-cube opener) — so every warmed line is a guaranteed cache hit, never a wasted synthesis.

Runs where the keys and the curriculum live (the box). A dry run needs no key and spends nothing.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:  # noqa: BLE001
    pass

from concordance import voice  # noqa: E402

CURR = Path("data") / "curriculum"

def _clean(s: str) -> str:
    return " ".join(str(s or "").split()).strip()


def spoken_lines():
    """EXACTLY what the lesson player (read.html) speaks aloud, verbatim, through NHSpeak: each EXAMPLE
    and each DECODABLE SENTENCE (auto-spoken as the step appears, and on 'hear it'). These recur
    identically for every learner of every cube, so voicing them once is pure long-term efficiency —
    and, unlike the rules/checks (which the console weaves into dynamic sentences), they are played
    byte-for-byte, so a warmed line is a guaranteed cache HIT at play time."""
    lines = []
    for p in sorted(CURR.glob("*_en.json")):
        try:
            units = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        if not isinstance(units, list):
            continue
        for u in units:
            if not isinstance(u, dict):
                continue
            if u.get("decodable_sentence"):
                lines.append(_clean(u["decodable_sentence"]))
            for ex in (u.get("examples") or []):
                lines.append(_clean(ex))
    return lines


def coach_openers():
    """The EXACT opening line the audio coach speaks for 'teach me <tongue>' — deterministic per cube,
    spoken to every learner who starts it. Generated by asking the console what it would say, so the
    warmed string matches the spoken one byte-for-byte."""
    out = []
    try:
        from concordance import console, coach
        present = set(coach._discover())
        for s in coach.subjects().get("subjects", []):
            sid = s.get("id")
            if sid not in present:
                continue
            try:
                r = console._learn("teach me " + (s.get("title") or sid))
                if r.get("kind") == "lesson" and r.get("spoken"):   # a real cube opener, not the picker
                    out.append(_clean(r["spoken"]))
            except Exception:  # noqa: BLE001 — a subject that doesn't open is simply skipped
                continue
    except Exception:  # noqa: BLE001
        pass
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Warm the operator's-voice cache with the lines the app "
                                             "actually speaks verbatim (guaranteed cache hits).")
    ap.add_argument("--dry-run", action="store_true", help="list what would be voiced; spend nothing")
    ap.add_argument("--limit", type=int, default=0, help="synthesize at most N NEW lines (0 = no cap)")
    args = ap.parse_args()

    phrases, seen = [], set()
    for s in spoken_lines() + coach_openers():
        if s and len(s) <= voice._MAX_CHARS and s not in seen:
            seen.add(s)
            phrases.append(s)

    print(f"warm-voice · {len(phrases)} distinct spoken lines "
          f"(examples + decodables + cube openers) · ~{sum(len(p) for p in phrases):,} characters")
    if args.dry_run:
        for p in phrases[:8]:
            print("   ·", p[:80])
        print(f"   … ({len(phrases)} total). Dry run — nothing synthesized, nothing spent.")
        return 0
    if not voice.configured():
        print("ELEVENLABS_API_KEY / ELEVENLABS_VOICE_ID not set — run where the operator's voice is wired.",
              file=sys.stderr)
        return 2

    hits = misses = fails = 0
    for i, p in enumerate(phrases, 1):
        if args.limit and misses >= args.limit:
            print(f"   reached --limit {args.limit} new lines; stopping.")
            break
        res = voice.speak(p)
        if res is None:
            fails += 1
            continue
        _, state = res
        if state == "hit":
            hits += 1
        else:
            misses += 1
            time.sleep(0.4)   # be a good neighbor to the API on a genuine synthesis
        if i % 25 == 0 or state == "miss":
            print(f"   [{i}/{len(phrases)}] {state:4}  {p[:64]}")
    print(f"\n  done · {hits} already kept · {misses} newly voiced · {fails} unavailable. "
          f"The kept lines now speak instantly and free, in the operator's voice.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
